#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

with open("requirements.txt", "r", encoding="utf-8") as fh:
    requirements = fh.read().splitlines()

setup(
    name="simpletk",
    version="1.0.0",
    author="viorelpuv",
    author_email="-",
    description="Простая библиотека для создания GUI на Python",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/simpletk",
    project_urls={
        "Bug Tracker": "https://github.com/yourusername/simpletk/issues",
        "Documentation": "https://github.com/yourusername/simpletk/wiki",
        "Source Code": "https://github.com/yourusername/simpletk",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
        "Natural Language :: Russian",
    ],
    packages=find_packages(exclude=["tests", "tests.*", "examples", "examples.*"]),
    py_modules=["simpletk"],
    python_requires=">=3.6",
    install_requires=requirements,
    include_package_data=True,
    package_data={
        "simpletk": ["py.typed"],
    },
    zip_safe=False,
    keywords="gui tkinter simple easy russian",
)
